### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [108]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()
print(car)
# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])
print(headers)

['Chevrolet Chevelle Malibu' 'Buick Skylark 320' 'Plymouth Satellite'
 'AMC Rebel SST' 'Ford Torino' 'Ford Galaxie 500' 'Chevrolet Impala'
 'Plymouth Fury iii' 'Pontiac Catalina' 'AMC Ambassador DPL'
 'Citroen DS-21 Pallas' 'Chevrolet Chevelle Concours (sw)'
 'Ford Torino (sw)' 'Plymouth Satellite (sw)' 'AMC Rebel SST (sw)'
 'Dodge Challenger SE' "Plymouth 'Cuda 340" 'Ford Mustang Boss 302'
 'Chevrolet Monte Carlo' 'Buick Estate Wagon (sw)'
 'Toyota Corolla Mark ii' 'Plymouth Duster' 'AMC Hornet' 'Ford Maverick'
 'Datsun PL510' 'Volkswagen 1131 Deluxe Sedan' 'Peugeot 504' 'Audi 100 LS'
 'Saab 99e' 'BMW 2002' 'AMC Gremlin' 'Ford F250' 'Chevy C20' 'Dodge D200'
 'Hi 1200D' 'Datsun PL510' 'Chevrolet Vega 2300' 'Toyota Corolla'
 'Ford Pinto' 'Volkswagen Super Beetle 117' 'AMC Gremlin'
 'Plymouth Satellite Custom' 'Chevrolet Chevelle Malibu' 'Ford Torino 500'
 'AMC Matador' 'Chevrolet Impala' 'Pontiac Catalina Brougham'
 'Ford Galaxie 500' 'Plymouth Fury iii' 'Dodge Monaco (sw)'
 'Ford Count

In [58]:
df.head()

Car   MPG  Cylinders  Displacement  Horsepower  \
0  Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1          Buick Skylark 320  15.0          8         350.0       165.0   
2         Plymouth Satellite  18.0          8         318.0       150.0   
3              AMC Rebel SST  16.0          8         304.0       150.0   
4                Ford Torino  17.0          8         302.0       140.0   

   Weight  Acceleration  Model Origin  
0  3504.0          12.0     70     US  
1  3693.0          11.5     70     US  
2  3436.0          11.0     70     US  
3  3433.0          12.0     70     US  
4  3449.0          10.5     70     US

1. How can you get help on `np.array`?

Call dir() on np.array.

Call dir() on car.

Note the difference. `car` has methods and attributes we can use.

In [116]:
# help can be accessed through numpy specific help functions; i.e. lookfor(), info(), source()
dir(np.array)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [115]:
dir(car)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

 2.What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [63]:
print(car.dtype)
print(mpg.dtype)
print(horsepower.dtype)

object
float64
float64


3.`numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
# np is an alias that directs to numpy. It is a naming convention that makes coding easier by shortening the phrase numpy

4.Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [30]:
#each of the listed arrays have 1 dimension. You can find this info by calling ndim

#example of how to get dimensions
mpg.ndim

1

5.Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [120]:
mpg*12

array([216. , 180. , 216. , 192. , 204. , 180. , 168. , 168. , 168. ,
       180. ,   0. ,   0. ,   0. ,   0. ,   0. , 180. , 168. ,   0. ,
       180. , 168. , 288. , 264. , 216. , 252. , 324. , 312. , 300. ,
       288. , 300. , 312. , 252. , 120. , 120. , 132. , 108. , 324. ,
       336. , 300. , 300. ,   0. , 228. , 192. , 204. , 228. , 216. ,
       168. , 168. , 168. , 168. , 144. , 156. , 156. , 216. , 264. ,
       228. , 216. , 276. , 336. , 360. , 360. , 372. , 420. , 324. ,
       312. , 288. , 300. , 276. , 240. , 252. , 156. , 168. , 180. ,
       168. , 204. , 132. , 156. , 144. , 156. , 228. , 180. , 156. ,
       156. , 168. , 216. , 264. , 252. , 312. , 264. , 336. , 276. ,
       336. , 324. , 156. , 168. , 156. , 168. , 180. , 144. , 156. ,
       156. , 168. , 156. , 144. , 156. , 216. , 192. , 216. , 216. ,
       276. , 312. , 132. , 144. , 156. , 144. , 216. , 240. , 252. ,
       264. , 216. , 228. , 252. , 312. , 180. , 192. , 348. , 288. ,
       240. , 228. ,

In [121]:
#another way to multiple the array
np.multiply(mpg,12)

array([216. , 180. , 216. , 192. , 204. , 180. , 168. , 168. , 168. ,
       180. ,   0. ,   0. ,   0. ,   0. ,   0. , 180. , 168. ,   0. ,
       180. , 168. , 288. , 264. , 216. , 252. , 324. , 312. , 300. ,
       288. , 300. , 312. , 252. , 120. , 120. , 132. , 108. , 324. ,
       336. , 300. , 300. ,   0. , 228. , 192. , 204. , 228. , 216. ,
       168. , 168. , 168. , 168. , 144. , 156. , 156. , 216. , 264. ,
       228. , 216. , 276. , 336. , 360. , 360. , 372. , 420. , 324. ,
       312. , 288. , 300. , 276. , 240. , 252. , 156. , 168. , 180. ,
       168. , 204. , 132. , 156. , 144. , 156. , 228. , 180. , 156. ,
       156. , 168. , 216. , 264. , 252. , 312. , 264. , 336. , 276. ,
       336. , 324. , 156. , 168. , 156. , 168. , 180. , 144. , 156. ,
       156. , 168. , 156. , 144. , 156. , 216. , 192. , 216. , 216. ,
       276. , 312. , 132. , 144. , 156. , 144. , 216. , 240. , 252. ,
       264. , 216. , 228. , 252. , 312. , 180. , 192. , 348. , 288. ,
       240. , 228. ,

In [122]:
mpg/12

array([1.5       , 1.25      , 1.5       , 1.33333333, 1.41666667,
       1.25      , 1.16666667, 1.16666667, 1.16666667, 1.25      ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.25      , 1.16666667, 0.        , 1.25      , 1.16666667,
       2.        , 1.83333333, 1.5       , 1.75      , 2.25      ,
       2.16666667, 2.08333333, 2.        , 2.08333333, 2.16666667,
       1.75      , 0.83333333, 0.83333333, 0.91666667, 0.75      ,
       2.25      , 2.33333333, 2.08333333, 2.08333333, 0.        ,
       1.58333333, 1.33333333, 1.41666667, 1.58333333, 1.5       ,
       1.16666667, 1.16666667, 1.16666667, 1.16666667, 1.        ,
       1.08333333, 1.08333333, 1.5       , 1.83333333, 1.58333333,
       1.5       , 1.91666667, 2.33333333, 2.5       , 2.5       ,
       2.58333333, 2.91666667, 2.25      , 2.16666667, 2.        ,
       2.08333333, 1.91666667, 1.66666667, 1.75      , 1.08333333,
       1.16666667, 1.25      , 1.16666667, 1.41666667, 0.91666

In [123]:
np.exp(mpg)

array([6.56599691e+07, 3.26901737e+06, 6.56599691e+07, 8.88611052e+06,
       2.41549528e+07, 3.26901737e+06, 1.20260428e+06, 1.20260428e+06,
       1.20260428e+06, 3.26901737e+06, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 3.26901737e+06,
       1.20260428e+06, 1.00000000e+00, 3.26901737e+06, 1.20260428e+06,
       2.64891221e+10, 3.58491285e+09, 6.56599691e+07, 1.31881573e+09,
       5.32048241e+11, 1.95729609e+11, 7.20048993e+10, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 1.31881573e+09, 2.20264658e+04,
       2.20264658e+04, 5.98741417e+04, 8.10308393e+03, 5.32048241e+11,
       1.44625706e+12, 7.20048993e+10, 7.20048993e+10, 1.00000000e+00,
       1.78482301e+08, 8.88611052e+06, 2.41549528e+07, 1.78482301e+08,
       6.56599691e+07, 1.20260428e+06, 1.20260428e+06, 1.20260428e+06,
       1.20260428e+06, 1.62754791e+05, 4.42413392e+05, 4.42413392e+05,
       6.56599691e+07, 3.58491285e+09, 1.78482301e+08, 6.56599691e+07,
      

In [124]:
np.sqrt(mpg)

array([4.24264069, 3.87298335, 4.24264069, 4.        , 4.12310563,
       3.87298335, 3.74165739, 3.74165739, 3.74165739, 3.87298335,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       3.87298335, 3.74165739, 0.        , 3.87298335, 3.74165739,
       4.89897949, 4.69041576, 4.24264069, 4.58257569, 5.19615242,
       5.09901951, 5.        , 4.89897949, 5.        , 5.09901951,
       4.58257569, 3.16227766, 3.16227766, 3.31662479, 3.        ,
       5.19615242, 5.29150262, 5.        , 5.        , 0.        ,
       4.35889894, 4.        , 4.12310563, 4.35889894, 4.24264069,
       3.74165739, 3.74165739, 3.74165739, 3.74165739, 3.46410162,
       3.60555128, 3.60555128, 4.24264069, 4.69041576, 4.35889894,
       4.24264069, 4.79583152, 5.29150262, 5.47722558, 5.47722558,
       5.56776436, 5.91607978, 5.19615242, 5.09901951, 4.89897949,
       5.        , 4.79583152, 4.47213595, 4.58257569, 3.60555128,
       3.74165739, 3.87298335, 3.74165739, 4.12310563, 3.31662

6.What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [13]:
np.sum(horsepower) #sum

42033.0

In [17]:
np.amin(horsepower) #min

0.0

In [18]:
np.amax(horsepower) #max

230.0

In [12]:
np.median(horsepower) #median

93.5

In [20]:
from scipy import stats
    
stats.mode(horsepower)         #mode

ModeResult(mode=array([150.]), count=array([22]))

7.Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [25]:
print(acceleration[0:5]) #first 5 elements

[12.  11.5 11.  12.  10.5]


In [26]:
print(acceleration[::2]) #everyother element

[12.  11.  10.5  9.  10.  17.5 11.  11.   8.   9.5 15.  15.5 14.5 17.5
 17.5 15.  15.  18.5 15.5 19.  13.  15.5 15.5 11.5 13.  12.  13.5 15.
 14.  19.5 19.  19.  15.5 23.5 16.5 12.  13.  11.  13.5 13.5 14.  14.
 18.  18.  17.  15.  13.  13.  12.5 12.  14.5 11.  16.5 16.  16.  14.
 13.  15.  19.5 13.5 14.  13.  19.5 14.  11.  13.5 16.5 16.  19.  21.
 17.  16.5 14.5 16.  16.5 14.5 19.  15.5 15.  16.  16.  19.5 14.  13.5
 18.5 19.  13.5 16.  16.  13.5 17.  14.  15.  14.5 17.5 16.9 17.7 13.
 13.9 15.4 17.6 22.2 14.2 17.7 16.2 12.2 16.4 15.7 21.9 16.7 12.  14.
 14.8 15.5 12.5 13.7 16.4 17.7 11.1 12.2 14.5 18.2 17.  16.4 14.5 13.5
 14.4 18.6 15.5 12.8 18.2 15.4 17.2 16.7 15.1 13.4 13.7 14.2 14.5 16.7
 14.9 13.6 15.8 16.6 18.2 18.2 15.4 13.2 14.9 15.  14.  14.4 20.1 24.8
 13.2 19.2 16.  12.9 14.7 15.5 16.5 20.1 15.8 17.5 15.2 14.4 21.7 19.9
 13.8 18.  11.4 15.1 17.  16.4 12.6 16.9 16.1 19.4 16.  16.2 14.2 14.4
 14.8 20.4 19.6 13.8 19.  16.6 18.6 16.2 18.  20.5 18.2 14.7 14.5 16.9
 15.7 16.4 1

8.Show how to select the number `99` in the array below. 

In [106]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

num_99 = select_99[1,2]
print(num_99)

99


9.Select the last element in each subarray (do this with one operation.)

In [46]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [10]:
def Ext(select_more): 
    return [item[-1] for item in select_more]

print(Ext(select_more))

[3, 6, 9]


10.Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [88]:
np.lookfor('log') #numpy.log was found so I ran np.log since numpy was imported as np


Search results for 'log'
------------------------
numpy.log
    Natural logarithm, element-wise.
numpy.log2
    Base-2 logarithm of `x`.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, element-wise.
numpy.logspace
    Return numbers spaced evenly on a log scale.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.logical_or
    Compute the truth value of x1 OR x2 element-wise.
numpy.logical_and
    Compute the truth value of x1 AND x2 element-wise.
numpy.logical_not
    Compute the truth value of NOT x element-wise.
numpy.logical_xor
    Compute the truth value of x1 XOR x2, element-wise.
numpy.ma.log
    Natural logarithm, element-wise.
numpy.ma.log2
    Base-2 logarithm of `x`.
numpy.ma.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.rec

In [56]:
np.log(mpg)

C:\Users\chdar\AppData\Local\Temp/ipykernel_7176/67066281.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(mpg)


array([2.89037176, 2.7080502 , 2.89037176, 2.77258872, 2.83321334,
       2.7080502 , 2.63905733, 2.63905733, 2.63905733, 2.7080502 ,
             -inf,       -inf,       -inf,       -inf,       -inf,
       2.7080502 , 2.63905733,       -inf, 2.7080502 , 2.63905733,
       3.17805383, 3.09104245, 2.89037176, 3.04452244, 3.29583687,
       3.25809654, 3.21887582, 3.17805383, 3.21887582, 3.25809654,
       3.04452244, 2.30258509, 2.30258509, 2.39789527, 2.19722458,
       3.29583687, 3.33220451, 3.21887582, 3.21887582,       -inf,
       2.94443898, 2.77258872, 2.83321334, 2.94443898, 2.89037176,
       2.63905733, 2.63905733, 2.63905733, 2.63905733, 2.48490665,
       2.56494936, 2.56494936, 2.89037176, 3.09104245, 2.94443898,
       2.89037176, 3.13549422, 3.33220451, 3.40119738, 3.40119738,
       3.4339872 , 3.55534806, 3.29583687, 3.25809654, 3.17805383,
       3.21887582, 3.13549422, 2.99573227, 3.04452244, 2.56494936,
       2.63905733, 2.7080502 , 2.63905733, 2.83321334, 2.39789

11.You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [26]:
#type(origin)
origin_test = [0,6,5,0,6,5]


array([0, 5, 6])

In [71]:
#np.unique gives the sorted elements of an array
np.unique(origin) 

array(['Europe', 'Japan', 'US'], dtype=object)

12.
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [125]:

#an array can be created through np.arrange or by using np.array command

#Example of 1D array with np.arrange
arrx = np.arange(3)
print(arrx)
arrx.ndim

#Question arrays
arr2 = np.array([[1,2,], [3,4]])
arr3 = np.array([[[1,2,3], [3,4,5], [6,7,8]]])
arr4 = np.array([[[[1,2,3], [3,4,5], [6,7,8]]]])

#Dimension of arr2
arr2.ndim

[0 1 2]


2

In [54]:
arr2.shape

(2, 2)

In [51]:
arr3.ndim

3

In [52]:
arr3.shape

(1, 3, 3)

In [131]:
(arr4.shape, arr4.ndim)

((1, 1, 3, 3), 4)

13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [113]:
origin == 'US'

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

14.Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [65]:
#index of US cars
car[origin=='US']

array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

15.Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

In [34]:
# np.array consumes less memory and has a better / faster runtime.  They also includes built in algebra functions 
# lists might be preferred when there are multiple element types. Lists can also be resized. 

16.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

In [13]:
# an identity matrix is a square matrix with the main diagonal consisting of ones

x = np.identity(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


17.Transpose the following array. 

In [18]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


transpose_me.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.Why does this multiplication operation fail? 

In [32]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

In [132]:
# This operation fails because the matrices differ in configurations (3,2) and (3,3) 

# This works if you make them matching configurations
arr1 = np.array([[1,2,3],
                      [4,5,6]])

arr2 = np.array([[1,2,3],
                      [4,5,6]])
#works when aligned
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36]])

Use numpy to answer the following questions. 

2.What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

In [136]:
np.average(horsepower[origin=='Europe'])

78.78082191780823

3.On average are Japanse cars more fuel efficient than US cars? 

In [130]:
(np.average(mpg[origin =='Japan']),np.average(mpg[origin =='US'])) #Japanese cars are more fuel efficient

(30.450632911392404, 19.688188976377955)

4.What is the correlation coefficient of `mpg` and `weight`? What is a correlaton coefficient?

In [126]:
# correlation coefficient quantifies how a variable or dataset moves in relation to another

array([[ 1.        , -0.78750994],
       [-0.78750994,  1.        ]])

# The Unix Shell

 #a shell reads and runs commands - at the command line prompt
 #There are two ways to create files; through a nano editor or a touch command 
 #>> is used to append text/data
